# Generated by Django 4.1 on 2022-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('pa', models.CharField(max_length=8)),
                ('dob', models.DateField()),
                ('g', models.EmailField(max_length=254)),
                ('ph', models.IntegerField(max_length=10)),
            ],
        ),
    ]
