# Generated by Django 4.1 on 2022-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='g',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ph',
            field=models.IntegerField(),
        ),
    ]
