# Generated by Django 4.1 on 2022-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0003_alter_customer_g_alter_customer_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pa',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ph',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
