# Generated by Django 4.1 on 2022-08-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0004_alter_customer_pa_alter_customer_ph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_train', to='Train.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Train.customer')),
            ],
        ),
    ]
